### ISSUE TITLE
MqttOpenTest java.lang.RuntimeException: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by kmarsden** [quarks-edge/quarks#30]
I am running the tests and they seemed to be progressing well but then I got the error below  on MqttOpenTest testConnectRetrySub

I am guessing this is user error of some sort, but wanted to see if anyone knows the solution off hand.

I am running on Windows 7

java.lang.RuntimeException: java.util.concurrent.TimeoutException

java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrrent.TimeoutException
at java.util.concurrent.FutureTask.report(FutureTask.java:123)
at java.util.concurrent.FutureTask.get(FutureTask.java:207)
at quarks.runtime.etiao.TrackingScheduledExecutor$TrackedFuture.gget(TrackingScheduledExecutor.java:238)
at quarks.topology.spi.tester.AbstractTester.complete(AbstractTester.java:32)
at quarks.test.topology.TopologyAbstractTest.complete(TopologyAbstractTest.java:59)
at quarks.test.topology.TopologyAbstractTest.completeAndValidate(TopologyAbstractTest.java:83)
at quarks.test.connectors.common.ConnectorTestBase.completeAndValidate(ConnectorTestBase.java:90)

at quarks.test.connectors.common.ConnectorTestBase.ccompleteAndValidate(ConnectorTestBase.java:79)
at quarks.test.connectors.mqtt.MqttStreamsTestManual.testCConnectRetrySub(MqttStreamsTestManual.java:916)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException
at quarks.runtime.etiao.Exeecutable.invokeAction(Executable.java:202)
at quarks.runtime.etiaao.Executable.start(Executable.java:154)
at quarks.runtime.etiao.EtiaoJob.stateChange(EtiaoJob.java:70)
at quarks.providers.direct.DirectTopology.execute(DirectTopology.java:73)
at quarks.providers.direct.DirectTTopology$1.call(DirectTopology.java:61)
at quarks.providers.direct.DirectTopology$1.call(DirectTopology.java:57)
at jjava.util.concurrent.FutureTask.run(FutureTask.java:267)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:1180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at quarks.runtime.etiao.TrackingScheduledExecutor$TrackedFuture.run(TrackingScheduledExecutorr.java:188)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
at java.util.concurrent.ThreadPooolExecutor$Worker.run(ThreadPoolExecutor.java:618)
at quarks.runtime.etiao.ThreadFactoryTracker$2.run(ThreadFactoryTracker.java:70)
at java.lang.Thread.run(Thread.java:785)
Caused by: java.util.concurrent.TimeoutException

**Comment by mnwone** [comment]
I'm also seeing the MqttOpenTest error on Wndows.  Attaching the output file.

[TEST-quarks.test.connectors.mqtt.MqttOpenTest.xml.TXT](https://github.com/quarks-edge/quarks/files/137271/TEST-quarks.test.connectors.mqtt.MqttOpenTest.xml.TXT)

**Comment by mnwone** [comment]
Also, PING test.mosquitto.org works fine.

**Comment by mnwone** [comment]
Is MqttStreamsTestManual.java intended to be executed in 'ant test'?
...
at quarks.test.connectors.mqtt.MqttStreamsTestManual.testConnectRetrySub(MqttStreamsTestManual.java:916)

**Comment by dlaboss** [comment]
the .TXT file indicates that most tests passes, two didn't: testMultiConnector, testConnectRetrySub with job startup timedout failures.  Are you both seeing these particular tests failing... each time it fails?  You can identify which tests fail by looking at the `<testcase` elements in the TXT and seeing which have a `<failure` child element.

Definitely not a "user error", nor test specific timing sensitivity.  Almost certain it doesn't have anything to do with public mqtt server availability.  I'm not seeing a problem from my Mac.

@mnwone, TestManual is just showing up because MqttOpenTest is a subclass of it so no worries there.  

@vdogaru, both reported timedout from EtiaoJob.stateChange() **starting** the job.  At least in the case of the latter one, it's clear from other output that at least some of the topology is executing fine.

**Comment by kmarsden** [comment]
testMultiConnector did not fail for me.  I actually have no <failure tags, just the <error for testConnectRetrySub.   I ran it in the Eclipse debugger and got some more output including a connection refused.  It does not pass with my firewall turned off temporarily.

***\* getCnt:1
Feb 19, 2016 4:01:53 PM quarks.connectors.runtime.Connector setStateUnsafe
INFO: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub state CONNECTING (was DISCONNECTED)
***\* getCnt:2
Feb 19, 2016 4:01:53 PM quarks.connectors.mqtt.runtime.MqttConnector newClient
INFO: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub server:tcp://localhost:31999 clientId:56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub actionTimeToWait:-1 persistence:org.eclipse.paho.client.mqttv3.persist.MemoryPersistence@f50c0a4
Feb 19, 2016 4:01:54 PM quarks.connectors.mqtt.runtime.MqttConnector doConnect
INFO: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub cleanSession:true userName:null password:null idleTimeout:0 idleReconnectTimeout:60 cnTimeout:30 keepalive:60 serverURIs:[tcp://localhost:31999] willDst:null willMsg:null
Feb 19, 2016 4:01:56 PM quarks.connectors.runtime.Connector oneConnect
SEVERE: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub doConnect() failed
Unable to connect to server (32103) - java.net.ConnectException: Connection refused: connect
    at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:619)
    at java.lang.Thread.run(Thread.java:785)
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:96)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:375)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:218)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.net.Socket.connect(Socket.java:658)
    at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
    ... 2 more

Feb 19, 2016 4:01:56 PM quarks.connectors.runtime.Connector connectTask
INFO: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub connectTask() waiting 2000msec to retry
***\* getCnt:3
Feb 19, 2016 4:01:58 PM quarks.connectors.mqtt.runtime.MqttConnector newClient
INFO: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub server:tcp://localhost:31999 clientId:56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub actionTimeToWait:-1 persistence:org.eclipse.paho.client.mqttv3.persist.MemoryPersistence@2fa31ba4
Feb 19, 2016 4:01:58 PM quarks.connectors.mqtt.runtime.MqttConnector doConnect
INFO: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub cleanSession:true userName:null password:null idleTimeout:0 idleReconnectTimeout:60 cnTimeout:30 keepalive:60 serverURIs:[tcp://localhost:31999] willDst:null willMsg:null
Feb 19, 2016 4:02:00 PM quarks.connectors.runtime.Connector oneConnect
SEVERE: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub doConnect() failed
Unable to connect to server (32103) - java.net.ConnectException: Connection refused: connect
    at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:619)
    at java.lang.Thread.run(Thread.java:785)
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:96)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:375)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:218)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.net.Socket.connect(Socket.java:658)
    at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
    ... 2 more

Feb 19, 2016 4:02:00 PM quarks.connectors.runtime.Connector connectTask
INFO: MQTT af1a5151 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_sub connectTask() waiting 4000msec to retry
Feb 19, 2016 4:02:00 PM quarks.connectors.runtime.Connector setStateUnsafe
INFO: MQTT 19c6ff5f 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_pub state CONNECTING (was DISCONNECTED)
Feb 19, 2016 4:02:00 PM quarks.connectors.mqtt.runtime.MqttConnector newClient
INFO: MQTT 19c6ff5f 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_pub server:tcp://test.mosquitto.org:1883 clientId:56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_pub actionTimeToWait:-1 persistence:org.eclipse.paho.client.mqttv3.persist.MemoryPersistence@1ce8e80
Feb 19, 2016 4:02:00 PM quarks.connectors.mqtt.runtime.MqttConnector doConnect
INFO: MQTT 19c6ff5f 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_pub cleanSession:true userName:null password:null idleTimeout:0 idleReconnectTimeout:60 cnTimeout:30 keepalive:60 serverURIs:[tcp://test.mosquitto.org:1883] willDst:null willMsg:null
Feb 19, 2016 4:02:00 PM quarks.connectors.runtime.Connector setStateUnsafe
INFO: MQTT 19c6ff5f 56155281_6248_41c6_b841_8c7ce046141c_testConnectRetrySub_pub state CONNECTED (was CONNECTING)
Completer timed out
Thread: pool-1-thread-1-testConnectRetrySub_JOB_0: task terminated with exception : java.lang.RuntimeException: java.util.concurrent.TimeoutException
java.lang.RuntimeException: java.util.concurrent.TimeoutException
    at quarks.runtime.etiao.Executable.invokeAction(Executable.java:202)
    at quarks.runtime.etiao.Executable.start(Executable.java:154)
    at quarks.runtime.etiao.EtiaoJob.stateChange(EtiaoJob.java:70)
    at quarks.providers.direct.DirectTopology.execute(DirectTopology.java:73)
    at quarks.providers.direct.DirectTopology$1.call(DirectTopology.java:61)
    at quarks.providers.direct.DirectTopology$1.call(DirectTopology.java:57)
    at java.util.concurrent.FutureTask.run(FutureTask.java:267)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at quarks.runtime.etiao.TrackingScheduledExecutor$TrackedFuture.run(TrackingScheduledExecutor.java:188)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:618)
    at quarks.runtime.etiao.ThreadFactoryTracker$2.run(ThreadFactoryTracker.java:70)
    at java.lang.Thread.run(Thread.java:785)
Caused by: java.util.concurrent.TimeoutException
    ... 14 more

**Comment by dlaboss** [comment]
closing as a dup of issue #49
