### ISSUE TITLE
MqttStreamsTestManual.testConnectFail fails with java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by mnwone** [quarks-edge/quarks#47]
OS: Rhel7
Mosquitto 1.4.2 

Start mosquitto:
From /homes/hny7/maywone/MQTT/org.eclipse.mosquitto-1.4.2
-bash-4.2$ installed/usr/local/sbin/mosquitto -v -c ~/MQTT/org.eclipse.mosquitto-1.4.2/mosquitto.conf –v

Run test:
ant -Dtest.base.pattern='**/MqttStreamsTestManual.java' test

Test run 1:
[unittests_run1.zip](https://github.com/quarks-edge/quarks/files/145191/unittests_run1.zip)
Excerpt from /homes/hny7/maywone/git/quarks/connectors/mqtt/unittests/

<testcase classname="quarks.test.connectors.mqtt.MqttStreamsTestManual" name="testConnectFail" time="10.019">
    <error message="java.lang.RuntimeException: java.util.concurrent.TimeoutException" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.TimeoutException
    at java.util.concurrent.FutureTask.report(FutureTask.java:133)
    at java.util.concurrent.FutureTask.get(FutureTask.java:217)
    at quarks.runtime.etiao.TrackingScheduledExecutor$TrackedFuture.get(TrackingScheduledExecutor.java:238)
    at quarks.topology.spi.tester.AbstractTester.complete(AbstractTester.java:32)
    at quarks.test.topology.TopologyAbstractTest.complete(TopologyAbstractTest.java:59)
    at quarks.test.topology.TopologyAbstractTest.completeAndValidate(TopologyAbstractTest.java:83)
    at quarks.test.connectors.common.ConnectorTestBase.completeAndValidate(ConnectorTestBase.java:90)
    at quarks.test.connectors.common.ConnectorTestBase.completeAndValidate(ConnectorTestBase.java:79)
    at quarks.test.connectors.mqtt.MqttStreamsTestManual.testConnectFail(MqttStreamsTestManual.java:490)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException
    at quarks.runtime.etiao.Executable.invokeAction(Executable.java:202)
    at quarks.runtime.etiao.Executable.start(Executable.java:154)
    at quarks.runtime.etiao.EtiaoJob.stateChange(EtiaoJob.java:70)
    at quarks.providers.direct.DirectTopology.execute(DirectTopology.java:73)
    at quarks.providers.direct.DirectTopology$1.call(DirectTopology.java:61)
    at quarks.providers.direct.DirectTopology$1.call(DirectTopology.java:57)
    at java.util.concurrent.FutureTask.run(FutureTask.java:277)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at quarks.runtime.etiao.TrackingScheduledExecutor$TrackedFuture.run(TrackingScheduledExecutor.java:188)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at quarks.runtime.etiao.ThreadFactoryTracker$2.run(ThreadFactoryTracker.java:70)
    at java.lang.Thread.run(Thread.java:785)
Caused by: java.util.concurrent.TimeoutException
</error>
# 

Test run 2:
Increase the timeout from 10s to 100s
In quarks.runtime.etiao.Executable.invokeAction, edit line 198, changing 10 to 100.
Future<Boolean> completed = completer.poll(10, TimeUnit.SECONDS);   //original
Future<Boolean> completed = completer.poll(100, TimeUnit.SECONDS);   //new

[unittests_run2_Using100s.zip](https://github.com/quarks-edge/quarks/files/145192/unittests_run2_Using100s.zip)

The result is slightly different:
<testcase classname="quarks.test.connectors.mqtt.MqttStreamsTestManual" name="testConnectFail" time="15.016">
    <error type="java.util.concurrent.TimeoutException">java.util.concurrent.TimeoutException
    at java.util.concurrent.FutureTask.get(FutureTask.java:216)
    at quarks.runtime.etiao.TrackingScheduledExecutor$TrackedFuture.get(TrackingScheduledExecutor.java:238)
    at quarks.topology.spi.tester.AbstractTester.complete(AbstractTester.java:32)
    at quarks.test.topology.TopologyAbstractTest.complete(TopologyAbstractTest.java:59)
    at quarks.test.topology.TopologyAbstractTest.completeAndValidate(TopologyAbstractTest.java:83)
    at quarks.test.connectors.common.ConnectorTestBase.completeAndValidate(ConnectorTestBase.java:90)
    at quarks.test.connectors.common.ConnectorTestBase.completeAndValidate(ConnectorTestBase.java:79)
    at quarks.test.connectors.mqtt.MqttStreamsTestManual.testConnectFail(MqttStreamsTestManual.java:490)
</error>

Note: I see similar results using the Really Small Message Broker.

**Comment by dlaboss** [comment]
pretty sure this is a dup of issue#30.

@vdogaru, Etiao start is timing out.   In this particular `testConnectFail()` case the test uses a bogus mqtt server url - i.e., it will never connect before the test times out.  

The connector makes a blocking call to connect to the server from the `Topology.events(Consumer<Consumer<T>> eventSetup)` `eventSetup.accept(Consumer<T>)`.  Suspect that that's causing the start timeout (from `Events.start()` processing).   Hope you can follow that :-)

Shouldn't `Events.start()` be doing the `eventSetup.accept(this)` from the `endlessEventSource` thread?

**Comment by dlaboss** [comment]
see pull request #49

**Comment by dlaboss** [comment]
fixed by merge #49
