### ISSUE TITLE
DevelopmentProviderTest - console.war not found & can't load StaticLoggerBinder 

### ISSUE THREAD

**Issue by mnwone** [quarks-edge/quarks#58]
<testcase classname="quarks.test.providers.dev.DevelopmentProviderTest" name="testMetricsEverywhere" time="0.539">
    <error message="java.lang.Exception: console.war not found.  Run &apos;ant&apos; from the top level quarks directory, or &apos;ant&apos; from &apos;console/servlets&apos; to create console.war under the webapps directory." type="java.lang.RuntimeException">java.lang.RuntimeException: java.lang.Exception: console.war not found.  Run &apos;ant&apos; from the top level quarks directory, or &apos;ant&apos; from &apos;console/servlets&apos; to create console.war under the webapps directory.
    at quarks.test.providers.dev.DevelopmentTestSetup.createTopologyProvider(DevelopmentTestSetup.java:20)
    at quarks.test.providers.dev.DevelopmentTestSetup.createTopologyProvider(DevelopmentTestSetup.java:13)
    at quarks.test.topology.TopologyAbstractTest.setup(TopologyAbstractTest.java:34)
Caused by: java.lang.Exception: console.war not found.  Run &apos;ant&apos; from the top level quarks directory, or &apos;ant&apos; from &apos;console/servlets&apos; to create console.war under the webapps directory.
    at quarks.console.server.HttpServer.getInstance(HttpServer.java:70)
    at quarks.providers.development.DevelopmentProvider.&lt;init&gt;(DevelopmentProvider.java:63)
    at quarks.test.providers.dev.DevelopmentTestSetup.createTopologyProvider(DevelopmentTestSetup.java:17)
</error>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
]]></system-err>
[TEST-quarks.test.providers.dev.DevelopmentProviderTest.xml.txt](https://github.com/quarks-edge/quarks/files/148646/TEST-quarks.test.providers.dev.DevelopmentProviderTest.xml.txt)

**Comment by home4slc** [comment]
@mnwone - I've added the slf4j.org logger jar in the console/server/build.xml file and will merge it soon.  With regard to the war file, as the output says, ant must be run from the quarks directory to build the console.war file prior to running any class that uses the console.  Since this class uses DevelopmentProvider it does use the console.

**Comment by vdogaru** [comment]
@home4slc @mnwone #66 fixes `Failed to load class "org.slf4j.impl.StaticLoggerBinder"`

**Comment by home4slc** [comment]
Sorry @vdogaru I didn't see your comment, pull request #72 added something to console/server/build.xml that should fix this too.
