### ISSUE TITLE
MqttOpenTest.testConnectRetrySub AssertionFailedError

### ISSUE THREAD

**Issue by mnwone** [quarks-edge/quarks#95]
The test output file is from Windows.
[TEST-quarks.test.connectors.mqtt.MqttOpenTest.xml.txt](https://github.com/quarks-edge/quarks/files/159182/TEST-quarks.test.connectors.mqtt.MqttOpenTest.xml.txt)

Here's an excerpt:
<testcase classname="quarks.test.connectors.mqtt.MqttOpenTest" name="testConnectRetrySub" time="15.246">
    <failure message="11bd1462_bb66_44ff_a1c1_4045e01339ff_testConnectRetrySub_sub contents:[]" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: 11bd1462_bb66_44ff_a1c1_4045e01339ff_testConnectRetrySub_sub contents:[]
    at quarks.test.topology.TopologyAbstractTest.completeAndValidate(TopologyAbstractTest.java:85)
    at quarks.test.connectors.common.ConnectorTestBase.completeAndValidate(ConnectorTestBase.java:90)
    at quarks.test.connectors.common.ConnectorTestBase.completeAndValidate(ConnectorTestBase.java:79)
    at quarks.test.connectors.mqtt.MqttStreamsTestManual.testConnectRetrySub(MqttStreamsTestManual.java:916)
</failure>

**Comment by dlaboss** [comment]
@mnwone pls close this.  I know Kathey was getting clean runs on Windows recently.  A new Apache Quarks Jira can be created if this happens again.  Thanks.
